//
//  NearByPlacesPresenter.swift
//  NearBy
//
//  Created by Heba on 4/18/20.
//  Copyright (c) 2020 Cognitev. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NearByPlacesPresentationLogic {
    func present(places: [NearByPlaces.ViewModel.Place])
    func present(trackingMood: String)
    func present(error: Errors)
}

class NearByPlacesPresenter: NearByPlacesPresentationLogic {
    weak var viewController: NearByPlacesDisplayLogic?
    
    func present(places: [NearByPlaces.ViewModel.Place]) {
        self.viewController?.display(places: places)
    }
    
    func present(trackingMood: String) {
        viewController?.display(trackingMood: trackingMood)
    }
    
    func present(error: Errors) {
        switch error {
        case .noData:
            let blankSlate = NearByPlaces.ViewModel.BlankSlate(image: "exclamation-button", description: "No data found !!")
            viewController?.display(blankSlate: blankSlate)
        case .fail:
            let blankSlate = NearByPlaces.ViewModel.BlankSlate(image: "error-icon", description: "Something went wrong !!")
            viewController?.display(blankSlate: blankSlate)
        }
    }
}
