//
//  NearByPlacesRouter.swift
//  NearBy
//
//  Created by Heba on 4/18/20.
//  Copyright (c) 2020 Cognitev. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol NearByPlacesRoutingLogic {}

protocol NearByPlacesDataPassing {
  var dataStore: NearByPlacesDataStore? { get }
}

class NearByPlacesRouter: NSObject, NearByPlacesRoutingLogic, NearByPlacesDataPassing {
  weak var viewController: NearByPlacesViewController?
  var dataStore: NearByPlacesDataStore?
}
